spring.application.name=departamentos-service
spring.data.mongodb.uri=${MONGO_URI}
server.port=8081

# --- Configuración de Actuator ---
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

# =========================================
# TRACING / ZIPKIN
# =========================================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans