spring.application.name=perfiles-service
server.port=8083

# Mongo
spring.data.mongodb.uri=${MONGO_URI}
# RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASS}
# nombres
rabbitmq.exchange=empleados-exchange
rabbitmq.queue.perfiles=perfiles-queue
rabbitmq.routingkey.creado=empleado.creado
rabbitmq.routingkey.eliminado=empleado.eliminado