spring.application.name=perfiles-service
server.port=8083

# Mongo
spring.data.mongodb.uri=${MONGO_URI}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Exchange y routing keys
rabbitmq.exchange=empleados.exchange
rabbitmq.routingkey.creado=empleado.creado
rabbitmq.routingkey.eliminado=empleado.eliminado