spring.application.name=empleados-service
spring.data.mongodb.uri=${MONGO_URI}
departamentos.url=${DEPARTAMENTOS_URL}

# --- Configuración de OpenAPI (Swagger) ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Escaneo de controladores para documentación
springdoc.packages-to-scan=com.empresa.empleados.controller

# --- Configuración de Resilience4j (Circuit Breaker) ---
resilience4j.circuitbreaker.instances.departamentosCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.departamentosCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.departamentosCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.departamentosCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.departamentosCB.permittedNumberOfCallsInHalfOpenState=3
# Umbral para llamadas lentas
resilience4j.circuitbreaker.instances.departamentosCB.slowCallDurationThreshold=3s

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}